package com.example.movies.utils

const val COROUTINE_EXCEPTION_HANDLER_TAG = "COROUTINE_EXCEPTION_HANDLER_TAG"
const val RESPONSE_HANDLER_TAG = "RESPONSE_HANDLER_TAG"
const val TOP_250_MOVIES_VIEW_MODEL_TAG = "TOP_250_MOVIES_VIEW_MODEL_TAG"
const val DETAILS_VIEW_MODEL_TAG = "DETAILS_VIEW_MODEL_TAG"